### PR TITLE
build.md: OpenIndiana switched to perl 5.36

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by jclulow** [comment]
Is the change in that file sufficient to build the gate on a stock OI system that has 5.34, you don't need to do the mediator business?

**Comment by mtelka** [comment]
> Is the change in that file sufficient to build the gate on a stock OI system that has 5.34, you don't need to do the mediator business?

Right.  The "mediator business" should be done automatically.  The default perl and system-perl mediators points to 5.34 now.

**Review by wiedi — APPROVED** [review]
The changes mentioned here worked for me, thanks :)

**Comment by jclulow** [comment]
With my apologies for the extreme delay, this has now been deployed to the site!

**Pull request merged**
