### PR TITLE
Mention changes necessary to build illumos-gate on latest OI

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by jlevon** [comment]
I think we should keep instructions for non-latest OI at least for a while, otherwise this will fox everyone who hasn't upgraded?

**Comment by pyhalov** [comment]
@jlevon Does it look better now?

**Comment by jlevon** [comment]
Looks good, thanks!

**Comment by jclulow** [comment]
Deployed -- https://illumos.org/docs/developers/build/#openindiana_1 -- Thanks!

**Pull request merged**
