### PR TITLE
build: update OI environment file recommendations

### PR DESCRIPTION
**Pull request by Bill-Sommerfeld**
More updates for openindiana.

### CODE REVIEW

**Comment by mtelka** [comment]
For Perl I prefer this: #91

**Review by mtelka — CHANGES_REQUESTED** [review]
The `ON_CLOSED_BINS` line is not needed too, because there is no consumer for it.

**Comment by mtelka** [comment]
> The `ON_CLOSED_BINS` line is not needed too, because there is no consumer for it.

Obviously, there is consumer for it.  The reason the line is not needed because it is already in `illumos.sh`.

**Comment by Bill-Sommerfeld** [comment]
> For Perl I prefer this: #91

Done

> > The `ON_CLOSED_BINS` line is not needed too, because there is no consumer for it.
> 
> Obviously, there is consumer for it. The reason the line is not needed because it is already in `illumos.sh`.

Done.

**Comment by mtelka** [comment]
> > For Perl I prefer this: #91
> 
> Done

Wouldn't it be simpler to somehow manage the #91 merged instead?

> > > The `ON_CLOSED_BINS` line is not needed too, because there is no consumer for it.
> > 
> > 
> > Obviously, there is consumer for it. The reason the line is not needed because it is already in `illumos.sh`.
> 
> Done.

Thanks.

**Comment by Bill-Sommerfeld** [comment]
> Wouldn't it be simpler to somehow manage the #91 merged instead?

This has adjacent deletions so just absorbing #91 into this one has less risk of merge conflicts.

**Pull request merged**
